### ISSUE TITLE
Source maps to help with debugging

### ISSUE THREAD

**Issue by softwaredoug** [o19s/splainer#11]
For issues like #7 it would be nice to have source maps.

**Comment by epugh** [comment]
@softwaredoug I looked a bit at this issue, and I tried out Splainer locally.   I can step through in the debugger both the splainer and the splainer-search files.  Additionally, if I edit the local splainer files, with a reload of the browser they show up.

However, one thing I've seen with Webpack is that edits to the source .js files get automagically loaded into the app, and we don't have that.   

I'm thinking to do this, we would be migrating to a modern build system like webpack.
