### ISSUE TITLE
Can't search for ampersands

### ISSUE THREAD

**Issue by softwaredoug** [o19s/splainer#23]
Recieved the following email. Splainer doesn't have a way to escape & unfortunately

> When trying to do a search for &, splainer seems to get a bit confused, encoding the ampersand and then splitting on the & in the search args:
> 
> ```
> &hl.snippets=3
> &start=0
> &facet.sort=count
> &q=
> &amp;
> &group.sort=score+desc
> &group=true
> ```
> 
> So, I end up with an empty &q=…
> 
> Any possible workaround for this?

**Comment by epugh** [comment]
Nothing has been done on this for almost four years, so closing as won't fix.  seems very edge case..
