### ISSUE TITLE
help. B&H Photo

### ISSUE THREAD

**Issue by yonichanowitz** [o19s/splainer#36]
as per your business partner Eric P. i was instructed to write this here.

we would like an option that presents percentage numbers next to  the thermometer bars that display the weight each search term has 
were having problems adding it to the `stackedChart.js` file.

thank you!

**Comment by epugh** [comment]
Yoni, sorry it took a couple of days to circle back to you, I ended up pinging @softwaredoug.   So splainer is open source, so features get implemented as people feel the itch to solve the problem.  If you look at https://github.com/o19s/splainer/graphs/contributors you can see some people who've all contributed to Splainer besides @softwaredoug.  

For your specific UI change, what I'd suggest is that you go ahead and make the UI change you'd like, and submit a PR for it.    Alternatively, if this is something you want "right now" and want to make sure it get's implemented, then let's chat about us doing a small engagement to put this feature in for you.

**Comment by epugh** [comment]
Yoni, we've updated Splainer.  Please give it a test!   If this is something you still want, and want to contribute a PR, please reopen theissue!
