### ISSUE TITLE
Support Elasticsearch 5.x

### ISSUE THREAD

**Issue by softwaredoug** [o19s/splainer#39]
Just as Quepid has a configuration option to support ES 5 vs 2, w should add that here. Here's what we should do

## Acceptance Criteria
- In the "start" screen, there should be a version dropdown for `0.x-2.x`. or `5.0+` next to the "URL" box. It should be unselected at first, but mandatory that it is selected.
- If the wrong version is selected is it possible to return an error indicating the user likely selected the wrong version (or self correct if the error is regards to fields vs stored_fields?)
- In the "tweak" side pull out, add a checkbox or selection for ES version. Changing the version should the persist like other settings
- Add the `esVer` to the splainer URL so I can send a URL to a friend so they can see the same results I see

**Comment by tomsen-san** [comment]
Fixing this would be cool! Wanted to use splainer for a demo but am on 5.x now so it doesn't work. Would give it a try to fix it, but workshop is like 'really soon' so won't be able to help out now.

**Comment by softwaredoug** [comment]
Fixed! :) Try it out http://splainer.io
