### ISSUE TITLE
Parsing of a Solr query with a percent (%) sign generates extra characters '25'

### ISSUE THREAD

**Issue by arafalov** [o19s/splainer#41]
Example query:

> http://localhost:8983/solr/zSlide18/select?defType=edismax&q=George&mm=100%

Parse:

> defType=edismax
> &q=George
> &mm=100%25

**Comment by softwaredoug** [comment]
This is a bit of an odd area, because %25 corresponds to the % character. Chrome also turns % or %25. Either that or Solr chokes on just a % because it expects a URL escape sequence

**Comment by arafalov** [comment]
It has to be somewhere in the Javascript library, as it happens in both Chrome and Firefox and even with Solr server not there.

**Comment by epugh** [comment]
@arafalov we just deployed an update Splainer, that has a much newer version of the "splainer-search" library.  Can you retest?

**Comment by arafalov** [comment]
It still seems to happen. But on the other hand, Solr now seems to complain if the URL has unescaped % as well. So, I am not entirely sure at which point of the stack this confusion is introduced.

I think it is safe to close for now until somebody else gets more clarity about it.

**Comment by epugh** [comment]
Thanks @arafalov about this!   I hope to get a Solr JSON format support into splainer, which would avoid some of these issues ;-)
