### ISSUE TITLE
Upgrade Build tools

### ISSUE THREAD

**Issue by softwaredoug** [o19s/splainer#42]
- Upgrade frontend build tools to same used as Quepid for single page app
- Document how to run in development mode, run unit tests, etc
- Fix Circle CI Build
- Upgrade Circle CI to 2.0
- Make sure passing tests
- Doug to review Splainer for functional testing

**Comment by epugh** [comment]
Circle CI Build - Done.   Upgrade to Circle 2.0 Done.   Docs on dev done.  Docs on unit tests, not done.  Frontend build tools, maybe partly done?   Added some easy to test links for "functional testing"..

**Comment by epugh** [comment]
See #47 which lists out what isn't done from this ticket!  Closing this one now.
