### ISSUE TITLE
Multivalue Fields are a bit funky

### ISSUE THREAD

**Issue by softwaredoug** [o19s/splainer#5]
We show an array of length 1. (Does Solr always return an array on MV fields). And for some reason highlighting doesn't work in the case that I saw. This is ok, but we should be able to do better.

**Comment by epugh** [comment]
@softwaredoug it only took 5 and a half years, but this is fixed.   Try it out on http://splainer.io.  

https://github.com/o19s/splainer-search/pull/81

a multivalue field nowlooks like "value1value2", but it's still better than the crap we had.  you can do json as well.   so "cast.character"
