### ISSUE TITLE
Solr 8.4.1 breaks Splainer

### ISSUE THREAD

**Issue by nathancday** [o19s/splainer#76]
I've been updating the TMDB example for Solr to use the lastest version (8.4.1) on [this fork](https://github.com/o19s/solr-tmdb/tree/solr8.4.1). Using that image seems to break all Splainer links [example-link](http://splainer.io/#?solr=http:%2F%2Flocalhost:8983%2Fsolr%2Ftmdb%2Fselect%3Fq%3Dtext_people_notf:%22william%20shatner%22%26fl%3Dtitle%20overview%20cast%20directors&fieldSpec=title%20overview%20cast%20directors) with a cryptic message "Error with your query. Double check that the URL is correct". Clicking the learn more in Solr link results in this:

```
0 7 text_all true true true all id title overview cast directors 10 true aouaoeuCRAZY_STRING!8_______ text_people_notf:"william shatner" 62362iueaiCRAZY_POST_STRING!_______ id title overview cast directors xml text_people_notf:"william shatner" text_people_notf:"william shatner" PhraseQuery(text_people_notf:"william shatner") text_people_notf:"william shatner" LuceneQParser 7.0 5.0 5.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
```

@worleydl has dug into this a little bit already and found that it works up until v8.2.0. He also noted that it might be related to [SOLR-13982](https://issues.apache.org/jira/browse/SOLR-13982).

**Comment by epugh** [comment]
@nathancday can you retest this after following this command: https://github.com/o19s/quepid/wiki/Troubleshooting-Solr-and-Quepid#compatibility-with-nosniff

I think this change fixes it!  It does in Solr land.

**Comment by nathancday** [comment]
I think this issue should have been closed. It was a problem with the default Solr config, where it was sending JSON as text (for easy viewing according to the comments in the code) but with the new no-sniff changes it causes an error. Is that accurate @worleydl ?

**Comment by epugh** [comment]
I am assuming that if you do:

```
curl -X POST -H 'Content-type:application/json' -d '{
  "update-queryresponsewriter": {
    "name": "json",
    "class": "solr.JSONResponseWriter",
    "content-type": "text/javascript;charset=UTF-8"
  }
}' http://localhost:8983/solr/gettingstarted/config
```

then it will work jsut fine with Splainer.   And if you don't do that, hten it won't!  WE could beef up the error messages on Splainer to communite this step, we did that in Quepid.

**Comment by epugh** [comment]
Okay, so I'm caling this fixed!
