### ISSUE TITLE
Repair ES TMDB index

### ISSUE THREAD

**Issue by nathancday** [o19s/splainer#80]
Not all fields from the `o19s/es-tmdb` repo are present (cast is an example). Is this due to people defacing the instance? Should we move it behind a proper proxy

**Comment by worleydl** [comment]
It's alive, see:
http://quepid-elasticsearch.dev.o19s.com:9206/tmdb/_search?pretty

It has less documents and a simpler schema.  I think we may need to update
it to use the es-tmdb config if we want to have it as a backup for that
dataset.

**Comment by epugh** [comment]
I think https://github.com/o19s/quepid-docker/tree/master/elasticsearch-loader needs some updating.

**Comment by epugh** [comment]
Could also rework the way we deploy so somehow always use the `o19s/es-tmdb` code...

**Comment by nathancday** [comment]
Ok I think I understand better now. I would advocate for us mirroring the `es-tmdb` schema? Is there history around why we don't? Happy to be the one who tries this out, b/c I think it would be a valuable safety against CORS problems for TLRE

**Comment by worleydl** [comment]
+1 for keeping it the same.  I'd avoid copy/pasting if we possible and try
to update the quepid-docker configuration to just utilize the es-tmdb repo
so we only have one place to edit.

**Comment by epugh** [comment]
Let me know if you need any pointers, the README should help you get it up and running.  you may need permissions to push images to our private Docker repo...

**Comment by epugh** [comment]
Close but not done on https://github.com/o19s/quepid/wiki/Troubleshooting-Elasticsearch-and-Quepid

**Comment by epugh** [comment]
This is done!
