### ISSUE TITLE
Splainer for Solr is adding pseudofields to the hl.fl, throwing an exception

### ISSUE THREAD

**Issue by binarymax** [o19s/splainer#81]
When using the unified highlighter, splainer will automatically add all fields to both the fl list AND the hl.fl list.  When using pseudofields (such as 'f:$dateBoost') in the Displayed Fields for Splainer, the highlighter does not see the pseudofield, and it throws a missing field exception.

**Comment by worleydl** [comment]
Fixed in 2.6.2 splainer-search: http://splainer.io/#?solr=http:%2F%2Fquepid-solr.dev.o19s.com:8985%2Fsolr%2Ftmdb%2Fselect%3Fq%3D*:*&fieldSpec=title:title%20tagline%20text_people%20overview%20release_date%20vote_average%20vote_count%20f:$dateBoost
