### ISSUE TITLE
Cursor in JSON ACE editor not typing where it appears in Safari

### ISSUE THREAD

**Issue by softwaredoug** [o19s/splainer#82]
Using Elasticsearch w/ the JSON editor. If you open a link in Safari, then try to edit the query in the settings, the cursor does not type where it appears. Seems to work fine in Chrome.

**Comment by epugh** [comment]
Just saw this issue about migrating to Monaco..  https://github.com/yasa-org/yasa/issues/17   I've taken one look at Monaco a few months ago, and it was a bit beyond me, however hoping that by watching this issue I'll learn ;-)

**Comment by epugh** [comment]
Is this still an issue?
