### ISSUE TITLE
Figured out why TMDB text_people comes back as "john,sally,bob" instead of "john, sally, bob"

### ISSUE THREAD

**Issue by epugh** [o19s/splainer#84]
snip = escapeHtml(subFieldValue.slice(0, 200));   It takes our Array and smashes it into a string.

I wonder why we do this snip?   It's a method of getHighlightSnippet(), which I think we are trying to get away from.  Lets not do highlighting unless I specified I wanted it to be highlighted!

Is this related to the   // TODO: In a future refactor just compute the snippets and store them out, don't use a function call in the template comment in docRow.js?

**Comment by worleydl** [comment]
When escapeHtml is passed an array it casts it to a String which JS by
default inserts commas between the elements.  There may be some renaming
todo, getHighlightSnippet just checks to see if there is highlighting but
if not it returns the default.  Most everything goes thru this function
whether highlighting is turned on or not.

To get spaces between the elements we'd need to update this method:
https://github.com/o19s/splainer-search/blob/master/services/normalDocSvc.js#L20
