### ISSUE TITLE
Connectivity problems with a localhost in Chrome

### ISSUE THREAD

**Issue by xxelka** [o19s/splainer#90]
The Splainer stopped working with a localhost due to recent changes in Chrome around security - CORS, for both Solr and Elasticsearch.
However, the error message says it's a network error and CORS needs to be configured.

It's worth either to fix the issue or change the error message or stop supporting Chrome.

The Firefox works just fine.
My chrome version is:   96.0.4664.45

**Comment by epugh** [comment]
I need to revamp all the docs, and honestly, maybe we just bite the bullet on CORS in Solr?
