### ISSUE TITLE
Eliminate use of Promise.create()

### ISSUE THREAD

**Issue by epugh** [o19s/splainer#93]
`promise.js` was removed from the `splainer-search` library, and is not used in Quepid.   It still is used in three places in this project.  We'd like to remove it completely, as it appears to make "grunt test" fail, somethign about the browser runing the tests dones't work.  Removing `promise.js` makes the tests run, but many fail due to `Promise.create()` being needed!

Remove some Tech Debt!!!

**Comment by epugh** [comment]
Discovered as part of #92 effort....   We currenlty have disabled the tests in CircleCI (via the Dockerfile) to avoid this issue...  Obviously not good long term.

**Comment by worleydl** [comment]
Addressed in the `opensearch_poc` branch.
